FROM node:18 AS build
WORKDIR /app

COPY package.json ./
RUN npm install


COPY . .
RUN npm run build --omit=dev

FROM nginx:alpine
COPY --from=build /app/dist/demostrador-fic-fe/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["/bin/ash", "-c", \
"echo API_URL=[$API_URL], && \
sed -i s#http://localhost#$API_URL#g /usr/share/nginx/html/main*.js && \
sed -i s#3000#$API_PORT#g /usr/share/nginx/html/main*.js && \
nginx -g 'daemon off;'"]